$VAR1 = [
          'text',
          ' redefinitions of named patterns '
        ];
=encoding utf8

This document is targeted at DocBook users who are considering switching from DocBook V4.x to DocBook V5.0. It describes differences between DocBook V4.x and V5.0 and provides some suggestions about how to edit and process DocBook V5.0 documents. There is also a section devoted to conversion of legacy documents from DocBook 4.x to DocBook V5.0.

At the time this was written the current version of DocBook V5.0 was VERSION. However, almost all of the information in this document is general and applies to any newer version of DocBook V5.0.


=head1 Introduction

The differences between DocBook V4.x and V5.0 are quite radical in some aspects, but the basic idea behind DocBook is still the same, and almost all element names are unchanged. Because of this it is very easy to become familiar with DocBook V5.0 if you know any previous version of DocBook. You can find a complete list of changes in DB5SPEC, here we will discuss only the most fundamental changes.


=head2 Finally in a namespace

All DocBook V5.0 elements are in the namespace L<http://docbook.org/ns/docbook>. XMLExtensible Markup Language namespaces are used to distinguish between different element sets. In the last few years, almost all new XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML vocabularies. DocBook V5.0 is following this design rule. Using namespaces in your documents is very easy. Consider this simple article marked up in DocBook V4.5:

    <article>
      <title>Sample article</title>
      <para>This is a really short article.</para>
    </article>

The corresponding DocBook V5.0 article will look very similar:

    <article xmlns="http://docbook.org/ns/docbook" …>
      <title>Sample article</title>
      <para>This is a really short article.</para>
    </article>

The only change is the addition of a default namespace declaration (C<<<   xmlns="http://docbook.org/ns/docbook" >>>
    B<>
    L<http://docbook.org/ns/docbook>


=head2 


    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE article PUBLIC '-//OASIS//DTD DocBook XML V4.5//EN'
                             'http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd'>
    <article lang="en">
      <title>Sample article</title>
      <para>This is a very short article.</para>
    </article>


    <?xml version="1.0" encoding="utf-8"?>
    <article xmlns="http://docbook.org/ns/docbook" version="5.0" xml:lang="en">
      <title>Sample article</title>
      <para>This is a very short article.</para>
    </article>



    B<>


=head2 

=over

=item -

I<>


=item -

I<>


=item -

I<>


=item -

I<>


=back


=head2 
L<http://www.oasis-open.org/docbook/xml/&version;/>L<http://docbook.org/xml/&version;/>


<col width="44%" /><col width="11%" /><col width="11%" /><col width="11%" /><col width="11%" /><col width="11%" /><hr  />

=head3 
L<http://docbook.org/schemas/5x.html>


L<http://docbook.org/xml/&version;/rng/docbook.rng>


L<http://docbook.org/xml/&version;/rng/docbook.rnc>


L<http://docbook.org/xml/&version;/dtd/docbook.dtd>


L<http://docbook.org/xml/&version;/xsd/docbook.xsd>


L<http://docbook.org/xml/&version;/sch/docbook.sch>
L<http://www.oasis-open.org/docbook/xml/&version;/>

=head3 
L<the reference part of DocBook: The Definitive Guide|http://docbook.org/tdg5/en/html/pt02.html>
    B<>


=head1 


=head2 


=head3 
L<nXML mode|http://www.thaiopensource.com/nxml-mode/>
=for html <img src="images/emacs.png" alt="Emacs with nXML mode provides guided editing and validation" />
C<<<   schemas.xml >>>C<<<   site-lisp/nxml/schema >>>
    <namespace ns="http://docbook.org/ns/docbook" uri="docbook.rnc"/>

    B<>
    C<<<   docbook.rnc >>>

C<<<   schemas.xml >>>
    <locatingRules xmlns="http://thaiopensource.com/ns/locating-rules/1.0">
      <namespace ns="http://docbook.org/ns/docbook" uri="docbook.rnc"/>
    </locatingRules>


=head3 

=for html <img src="images/oxygen4.png" alt="DocBook V5.0 document opened in oXygen" />
=for html <img src="images/oxygen5.png" alt="DocBook V5.0 document opened in oXygen in Author mode" />

=head3 

=for html <img src="images/xxe.png" alt="XML Mind XML Editor – feels almost like MS Word but real DocBook V5.0 markup is created" />


=head2 



=head3 
L<http://relaxng.org/#validators>

C<<<   relames.zip >>>L<https://msv.dev.java.net/servlets/ProjectDocumentList?folderID=101>


     -Xss512K -jar relames.jar docbook.rng document.xml

    B<>
    C<<<   -Xss512K >>>

L<on-line DocBook V5.0 validator|http://relaxed.vse.cz/docbookvalidator/>

=head3 

L<http://nvdl.org/>
C<<<   onvdl-20070517.zip >>>


     -jar bin/onvdl.jar docbook.nvdl document.xml

L<http://sourceforge.net/project/showfiles.php?group_id=164464>

C<<<   jnvdl.bat >>>C<<<   jnvdl.sh >>>C<<<   -Xss512K >>>C<<<   java >>>

     -nt -s docbook.nvdl document.xml


     -nt -s docbook.nvdl document.xml


=head2 


=head3 



    Note: namesp. cut : stripped namespace before processing
    Note: namesp. cut : processing stripped document


=over

=item -




=item -




=back

    B<>
    
        WARNING: cannot add @xml:base to node set root element. Relative paths may not work.


=head3 
L<XSL-NS stylesheets|http://docbook.sourceforge.net/release/xsl-ns/current/>
L<docbook-xsl-ns|https://sourceforge.net/project/showfiles.php?group_id=21935&package_id=219178>

=head3 


=over

=item -




=item -




=item -




=item -




=back


L<http://docbook.sourceforge.net/snapshots/docbook-xsl2-snapshot.zip>L<http://saxon.sf.net>

     -jar saxon9.jar -o output.html document.xml docbook-xsl2-snapshot/html/docbook.xsl


     -jar saxon9.jar document.xml docbook-xsl2-snapshot/html/chunk.xsl


=head1 


=head2 


    <section id="dir">
      <title>DIR command</title>
      <para>...</para>
    </section>
    
    <section id="ls">
      <title>LS command</title>
      <para>This command is a synonym for <link linkend="dir"><command>DIR</command></link> command.</para>
    </section>


    <section xml:id="dir">
      <title>DIR command</title>
      <para>...</para>
    </section>
    
    <section xml:id="ls">
      <title>LS command</title>
      <para>This command is a synonym for <command linkend="dir">DIR</command> command.</para>
    </section>


    <article xmlns="http://docbook.org/ns/docbook" 
             xmlns:xl="http://www.w3.org/1999/xlink" version="5.0">
      <title>Test article</title>
    
      <para><application xl:href="http://www.gnu.org/software/emacs/emacs.html">Emacs</application> 
        is my favourite text editor.</para>
      …


    <ulink url="http://docbook.org">DocBook site</ulink>


    <link xl:href="http://docbook.org">DocBook site</link>


    <command xl:href="#dir">DIR</command>



=head2 



=head2 

C<<<   < remap="action"> >>>C<<<   < class="other"
  otherclass="medialabel"> >>>C<<<   <
  pubwork=""> >>>C<<<   <
  remap=""> >>>

=head1 

C<<<   doc.xml >>>

C<<<   doc.xml >>>C<<<   newdoc.xml >>>C<<<   db4-upgrade.xsl >>>




=head2 


I<>
C<<<   &Product; >>>C<<<   [[[Product]]] >>>C<<<   [[[Product]]] >>>
C<<<   <!DOCTYPE >>>C<<<   ]> >>>



C<<<   PUBLIC >>>C<<<   SYSTEM >>>
    <!DOCTYPE book [
    <!ENTITY someEntity "some replacement text">
    ]>


    B<>
    L<cloak script|http://docbook.svn.sourceforge.net/viewvc/docbook/trunk/contrib/tools/cloak>


=head3 

C<<<   db4-entities.pl >>>
C<<<   db4-entities.pl >>>


=head1 


=head2 

C<<<   db.halign.enumeration >>>C<<<   db.videodata.align.enumeration >>>C<<<   db.imagedata.align.enumeration >>>C<<<   db.videodata.align.attribute >>>C<<<   db.imagedata.align.attribute >>>

=head3 

=over

=item -




=item -




=item -

C<<<   db. >>>C<<<   db. >>>C<<<   db.figure.info >>>C<<<   db.cals.entrytbl.thead >>>


=item -

C<<<   db..attribute >>>C<<<   db..attribute >>>C<<<   db.olink.localinfo.attribute >>>C<<<   db.effectivity.attributes >>>


=item -

C<<<   db..attlist >>>C<<<   db..attlist >>>C<<<   db.html.table.attlist >>>C<<<   db.cals.table.attlist >>>


=item -

C<<<   db..enumeration >>>C<<<   db.verbatim.continuation.enumeration >>>C<<<   db.class.enumeration >>>


=item -




C<<<   db.error.inlines >>>C<<<   db.errorcode >>>C<<<   db.errortext >>>


C<<<   db.verbatim.blocks >>>C<<<   db.programlisting >>>C<<<   db.screen >>>


C<<<   db.effectivity.attributes >>>


C<<<   db.navigation.components >>>C<<<   db.glossary >>>C<<<   db.bibliography >>>C<<<   db.index >>>C<<<   db.toc >>>


C<<<   db.admonition.contentmodel >>>



=back


=head2 



bar



=head1 


=head2 

=head3 


C<<<   db.author >>>C<<<   dbx.person >>>C<<<   db.author >>>C<<<   dbx.person >>>
C<<<   {.rng}
  <?xml version="1.0" encoding="UTF-8"?>
  <grammar xmlns:db="http://docbook.org/ns/docbook"
           ns="http://docbook.org/ns/docbook"
           xmlns="http://relaxng.org/ns/structure/1.0">
    <include href="docbook.rng"/>
    <!-- define the new element -->
    <define name="dbx.person">
      <element name="person">
          <ref name="db.author.attlist"/>
          <ref name="db.credit.contentmodel"/>
      </element>
    </define>
    <!-- redefine the db.author pattern to allow db.person in
         the same places as db.author -->
    <define name="db.author" combine="choice">
      <ref name="dbx.person"/>
    </define>
  </grammar>
 >>>



=head1 


=head1 

=head1 


C<<<   dbx.asm.inlines >>>C<<<   db.programming.inlines >>>C<<<   db.os.inlines >>>
C<<<   {.rng}
  <?xml version="1.0" encoding="UTF-8"?>
  <grammar xmlns:db="http://docbook.org/ns/docbook"
           ns="http://docbook.org/ns/docbook"
           xmlns="http://relaxng.org/ns/structure/1.0">
    <include href="docbook.rng"/>
    <!-- define the new elements -->
    <define name="dbx.register">
      <element name="register">
        <text/>
      </element>
    </define>
    <define name="dbx.instruction">
      <element name="instruction">
        <text/>
      </element>
    </define>
    <!-- create a new pattern that contains the new inlines -->
    <define name="dbx.asm.inlines">
      <choice>
        <ref name="dbx.register"/>
        <ref name="dbx.instruction"/>
      </choice>
    </define>
    <!-- add the new inlines to programming and os inlines -->
      <define name="db.programming.inlines" combine="choice">
        <ref name="dbx.asm.inlines"/>
      </define>
      <define name="db.os.inlines" combine="choice">
        <ref name="dbx.asm.inlines"/>
      </define>
  </grammar>
 >>>



=head1 


=head1 


=head1 


=head3 
C<<<   notAllowed >>>

C<<<   {.rng}
  <?xml version="1.0" encoding="UTF-8"?>
  <grammar xmlns:db="http://docbook.org/ns/docbook"
           ns="http://docbook.org/ns/docbook"
           xmlns="http://relaxng.org/ns/structure/1.0">
    <include href="docbook.rng">
      <!-- redefine important element as notAllowed -->
      <define name="db.important">
        <notAllowed/>
      </define>
    </include>
  </grammar>
 >>>



=head3 
C<<<   db.person.author.contentmodel >>>C<<<   db.org.author.contentmodel >>>C<<<   db.person.author.contentmodel >>>






    <author>
      <personname>Babe Ruth</personname>
      <born>02/06/1895</born>
      <died>08/16/1948</died>
    </author>

C<<<   db.org.author.contentmodel >>>
    <!-- INVALID -->
    <author>
      <orgname>Boston Red Sox</orgname>
      <died>1919</died>
      <born>2004</born>
    </author>


=head2 

=head3 
C<<<   db.author.attlist >>>






C<<<   db.person.author.contentmodel >>>
C<<<   {.rng}
  <?xml version="1.0" encoding="UTF-8"?>
  <grammar xmlns:db="http://docbook.org/ns/docbook"
           ns="http://docbook.org/ns/docbook"
           xmlns="http://relaxng.org/ns/structure/1.0">
    <include href="docbook.rng"/>
    <!-- redefinitions of named patterns -->
    <define name="db.person.author.contentmodel" combine="interleave">
      <interleave>
        <optional>
          <attribute name="born">
            <ref name="db.date.contentmodel"/>
          </attribute>
        </optional>
        <optional>
          <attribute name="died">
            <ref name="db.date.contentmodel"/>
          </attribute>
        </optional>
      </interleave>
    </define>
  </grammar>
 >>>



=head1 



=head3 
C<<<   empty >>>C<<<   notAllowed >>>C<<<   db.common.linking.attributes >>>C<<<   empty >>>
C<<<   {.rng}
  <?xml version="1.0" encoding="UTF-8"?>
  <grammar xmlns:db="http://docbook.org/ns/docbook"
           ns="http://docbook.org/ns/docbook"
           xmlns="http://relaxng.org/ns/structure/1.0">
    <include href="docbook.rng">
      <define name="db.common.linking.attributes">
        <empty/>
      </define>
    </include>
  </grammar>
 >>>


C<<<   empty >>>C<<<   notAllowed >>>

=head3 
C<<<   db.spacing.enumeration >>>
C<<<   {.rng}
  <?xml version="1.0" encoding="UTF-8"?>
  <grammar xmlns:db="http://docbook.org/ns/docbook"
           ns="http://docbook.org/ns/docbook"
           xmlns="http://relaxng.org/ns/structure/1.0">
    <include href="docbook.rng"/>
    <!-- add value to an enumeration -->
    <define name="db.spacing.enumeration" combine="choice">
      <value>large</value>
    </define>
  </grammar>
 >>>



=head1 


=head2 
L<http://docbook.org/ns/docbook>
    <book xmlns="http://docbook.org/ns/docbook"
          version="5.0">
      …
    </book>




    -[subset|extension|variant] [[-]?]+


    5.0-subset simplified-1.0
    5.0-variant ASMBook
    5.0-variant ASMBook-2006
    5.0-extension MathML-2.0 SVG-1.1


C<<<   subset >>>C<<<   extension >>>C<<<   variant >>>


=head1 

=head2 
B<>
B<>
B<>
B<>
L<Entity definition files|http://www.w3.org/2003/entities/>
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE article [
    <!ENTITY % isopub SYSTEM "http://www.w3.org/2003/entities/iso8879/isopub.ent">
    %isopub;
    ]>
    <article xmlns="http://docbook.org/ns/docbook" version="5.0">
    <title>DocBook V5.0 &ndash; the superb documentation format</title>
    …


    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE article [
    <!ENTITY % allent SYSTEM "http://www.w3.org/2003/entities/2007/w3centities-f.ent">
    %allent;
    ]>
    <article xmlns="http://docbook.org/ns/docbook" version="5.0">
    <title>DocBook V5.0 &ndash; the superb documentation format</title>
    …

B<>
B<>L<XInclude|http://www.w3.org/TR/xinclude/>C<<<   docbookxi.rnc >>>C<<<   docbook.rnc >>>
B<>
B<>
     -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration -jar bin/onvdl.jar docbook.nvdl document.xml

C<<<   -xi >>>

=head2 
B<>
B<>


=head2 
B<>
B<>

L<http://yupotan.sppd.ne.jp/relax-ng/mml2.html>C<<<   mathml >>>
C<<<   dbmathml.rnc >>>


C<<<   dbmathml.rng >>>




C<<<   dbmathml.rnc >>>C<<<   dbmathml.rng >>>
B<>
B<>
L<http://www.w3.org/Graphics/SVG/1.1/rng/rng.zip>C<<<   svg >>>
C<<<   dbsvg.rnc >>>


C<<<   dbsvg.rng >>>




C<<<   dbsvg.rnc >>>C<<<   dbsvg.rng >>>
B<>
B<>








B<>
B<>
=over

=item -

L<Sample customization of ITS and DocBook|http://www.w3.org/TR/xml-i18n-bp/#docbook-plus-its>


=item -

L<Examples on DocBook WiKi|http://wiki.docbook.org/topic/DocbookSchemas>


=back


=head2 
B<>C<<<   docbook.xsd >>>
B<>C<<<   xml.xsd >>>C<<<   xml.xsd >>>
L<http://relaxng.org/compact-tutorial-20030326.html>
L<http://jnvdl.sourceforge.net/tutorial.html>
L<http://www.w3.org/TR/xml-id/>
L<http://www.docbook.org/specs/wd-docbook-docbook-5.0a1.html>
C<<<   0 >>>C<<<   1 >>>







C<<<   docbook.rng >>>L<http://docbook.org/xml/VERSION/rng/docbook.rng>L<XML catalogs|http://www.oasis-open.org/committees/download.php/14809/xml-catalogs.html>
